### ISSUE TITLE
Ubermag 0.6 todo list

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#112]
Here we collect general to-do items we need to address before the 0.6 release:

- [ ] Review affiliations in README (@marijanbeg).
- [x] Add [Ubermag paper](https://ieeexplore.ieee.org/document/9427472) to How to Cite section (@marijanbeg).
- [x] Delete JOOMMF YouTube channel (@fangohr)
- [ ] Review the content of README file template (@marijanbeg, @fangohr)
- [x] Review CI for all packages (main and stable branches, release workflow, docs on gh-pages branch,...) (@marijanbeg)
- [x] #166
- [x] Update docker image(s) on DockerHub (@marijanbeg, @lang-m)
- [x] Ensure change-log is up-to-date (@lang-m)
- [x] Ensure all new functionality is documented and in the ~`workshop`~`tutorials` repository.
- [ ] Review meta-data (description, tags, etc.) for all repositories.
