### ISSUE TITLE
Ubermag release 2024.06

### ISSUE THREAD

**Issue by samjrholt** [ubermag/ubermag#176]
- [ ] ubermag/discretisedfield#525
- [ ] ubermag/mag2exp#65
- [ ] ubermag/mag2exp#62
- [ ] ubermag/mag2exp#63
- [ ] ubermag/mag2exp#54 Close
- [ ] ubermag/ubermagtable#56
- [ ] ubermag/ubermag#175
- [ ] ubermag/mumax3c#86
- [ ] ubermag/mumax3c#81
- [ ] ubermag/mumax3c#84
- [ ] ubermag/micromagnetictests#49
- [ ] ubermag/micromagnetictests#48 (maybe)
- [ ] ubermag/micromagnetictests#46
- [ ] ubermag/micromagneticmodel#87
- [ ] ubermag/micromagneticmodel#84
- [ ] ubermag/micromagneticmodel#83
- [ ] ubermag/micromagneticmodel#75 (maybe)
- [ ] ubermag/micromagneticdata#69
- [ ] ubermag/micromagneticdata#66
- [ ] ubermag/ubermagutil#50
- [ ] ubermag/turotials#70
- [ ] ubermag/tutorials#71
- [ ] ubermag/turotials#72
- [ ] ubermag/oommfc#138
- [ ] ubermag/oommfc#153
- [ ] ubermag/oommfc#133
